- lists/src/first.rs
- text/first.md
- Switched to `unimplemented!()` instead of `unreachable!()` since the statement in question is in fact reachable.
- Added a note about diverging functions.
> Minor corrections

- text/first-new.md
- text/first-pop.md
- text/second-into-iter.md
- text/second-iter.md
Thanks for writing this, it's really good. Here are some typo fixes in the code examples I came across. (Also a markdown formatting error.)
> Code typos, and add missing `pub`s

- text/first-pop.md
Spotted a missing link to diverging functions, which I guess should go to the Rust book.
This book is awesome! Thanks for making it :heart:
> Fix broken link to diverging functions

- text/first-layout.md
- text/first-new.md
- text/first-ownership.md
- text/first-pop.md
- text/first-push.md
Hi!
I liked reading this and felt like contributing some proofreading if you don't mind.
Of the things I didn't touch, why "an `&mut`"?
> Fix some typos

- README.md
Replaces old instructions of compiling rustc from scratch.
Instead of compiling rustc, I've found a [mirror](https://github.com/steveklabnik/rustbook) of the rustbook code.
Both rustbook and the book compile without problems on my Linux box:
Arch Linux x86_64 (kernel 4.1.3-1-ARCH)
rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)
cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-30)
I'm fairly certain most people will want to avoid bootstrapping the entire rustc compiler if the mirror works just as well.
> Add instructions for rustbook build via mirror

- text/fifth-basics.md
Used to say push, when the operation in question is pop.
> Simple typo with wrong operation

- text/second-iter.md
Added missing generic parameter to return value of the constructor method. The subsequent error messages now correspond to what is described in the text.
> Added missing generic parameter to iter constructor function.

- text/fourth-symmetry.md
The first assert of the "back" methods should call `pop_back`, not `pop_front`. It's already that way in the source file (lists/src/fourth.rs).
> Fix typo in tests of fourth list

- text/second-into-iter.md
Add an assert to completely test pop() when it should return None.
If that's OK with you I can submit some other patches to do the same for iter and itermut.
> more torough test

- text/first-drop.md
I don't know if this was intentional, e.g. for illustration purposes. But somehow I don't think so.
> Fixed typos in the Drop trait example implementations for the "bad stack list".

- .travis.yml
I think it is convenient to have an offline version of the book for download as well, so I wrote this Travis CI config to do that. With it Travis CI can take care of releasing a zip archive of the HTML book on tag. Creating a release on Github also triggers it to append the archive to the release.
Of course, you need to go to Travis CI to enable it for this repo. It also requires env var `GH_DEPLOY_TOKEN` be filled with a Github personal access token with "public_repo" enabled. This can be set in the Settings tab in the Travis CI page of this repo.
> Add Travis CI config to release built HTML book on tag

- lists/src/second.rs
- text/second-peek.md
This commit fixes #44.  I wondered the same thing and made some of the same mistakes as @alopatindev before stumbling on a way to mutate the reference inside of the `Option` returned by `peek_mut`.
> Try to mutate peek, failing once in the process

- src/second-iter-mut.md
Thank you for the book.
Here is one mistake that was found while reading "An ok stack: 3.6 IterMut". 
Compiler errors log described next to the code appears if `self` borrowed as `&mut`.
But in "3.7 Final Code" that moment is correct
> Fix typo, add "mut"

- .gitignore
- README.md
Rustbook has been largely [re-implemented](https://github.com/rust-lang/rust/tree/master/src/tools/rustbook) in terms of [mdBook](https://github.com/azerupi/mdBook), the rust books have been [ported](https://github.com/rust-lang/rust/pull/39633) to mdBook, and the README's install instructions are wildly out of date by now.
I'd like to propose changing the build instructions to use mdBook, which appears to be better-maintained, at least because `cargo install mdbook` is a little simpler than cloning and building rustbook.
The build process is about the same and works just as well as rustbook did.
> Update README to use mdbook over rustbook

- src/second-iter-mut.md
I believe the corrected version was intended to be shown, but it looks like there was a `mut` missing. Must have been a silly copy-paste error 😄
> add `mut` to corrected iter_mut definition

- src/second-iter-mut.md
Hello,
I was reading the tutorial and noticed a missing link for 'ownership' in the `IterMut` section of the `An Ok Stack` chapter. I added the link to the ownership chapter of the book, but not sure if this was the original intention.
> Fix missing link to ownership

- src/fourth-iteration.md
Fix for https://github.com/rust-unofficial/too-many-lists/issues/113
> fix issue 113: missing borrow in example code section 5.6

- src/first-pop.md
change `self.head` to `&self.head` to maintain consistency
> Fix pop example inconsistency

- src/README.md
Note that this replaces  https://doc.rust-lang.org/book/slice-patterns.html (now https://doc.rust-lang.org/1.8.0/book/slice-patterns.html) with https://doc.rust-lang.org/edition-guide/rust-2018/slice-patterns.html.
> Fix broken link to slice patterns

- src/second-iter.md
Added missing params to the lifetime example.
> add missing params

- src/second-iter.md
Remove `lists::` from cargo build command
> remove `lists::` -- I assume this is a typo

- src/third-drop.md
Remove `src::` from the `cargo test` command.
> remove extra text from the test command

- src/first-layout.md
- The node with junk should have a comma, similar to the other nodes
- Make clear that "allocated" means "heap-allocated"
> use commas and clarify allocation in foolish list

- src/third-layout.md
**This PR**
Just fixes a small typo at the end of the "Layout" section for the persistent linked list.
> Fix typo in Layout section of persistent list

- lists/src/fifth.rs
- lists/src/second.rs
- lists/src/third.rs
- src/fifth-extras.md
- src/fifth-final.md
- src/fifth-layout.md
- src/second-final.md
- src/second-iter-mut.md
- src/second-iter.md
- src/third-basics.md
- src/third-final.md
This update simplifys things thanks to rust 1.40 and now lists look a lot less scary for beginners. 
(Fixes #154 )
> Updating to make use of Rust 1.40 as_deref() and as_deref_mut()

- src/first-layout.md
The existing metaphor has some potentially unpleasant connotations and can be replaced without loss of clarity.
> reword an awkward metaphor

- src/fifth-layout.md
- src/fifth-unsafe.md
- src/first-push.md
- src/second-iter-mut.md
- src/second-iter.md
- src/third-layout.md
* capitalise Rust when it's a proper noun
* replace -- with — html entity (all usages are em dashes)
* remove apostrophe in "First things first"
* small typos
> Grammar and spelling fixes

- lists/src/third.rs
- src/third-basics.md
- src/third-final.md
Renamed all occurrences of the `append` function to `prepend` since the behaviour of the function is to add an element to the beginning of a list, not the end (as `append` should do).
> [Chapter 3] Rename `append` to `prepend`.

- src/fifth-layout.md
- src/third-layout.md
Change `&emdash;` to `&mdash`.
> Fix character entity references for em dashes

- src/README.md
- src/fifth-extras.md
- src/fifth-layout.md
- src/fourth-iteration.md
- src/third-basics.md
This makes a few minor changes I noticed as I was working through the book. The typos themselves are very minor (extra/missing spaces). The actual code changes are in separate commits; one of the `mod tests` was missing a `#[cfg(test)]` and a code snippet from towards the end of the Unsafe Queue didn't compile (nor match the same snippet from the Final Code for the section) without prose explaining that it is an expected failure.
> Fix compilation error and typos

- src/second-peek.md
That causes an invalid ePub file rendered by `mdbook-epub`.
> Type name not rendered correctly without backticks

- src/fifth-testing-stacked-borrows.md
There was code and resulting error message mismatch:
code was `let sref3 = &*mref1;`
and error is `casting `&&mut i32` as `*mut i32` is invalid`.
Then the phrase goes: Let's properly reborrow it with let sref3 = &mref1
But it should be the opposite:
`let sref3 = &mref1;` gives `&&mut i32`
> fixed mistake in "testing stacked borrows"
